server:
  servlet:
    context-path: "/tspn/pubsub/v1"
  port: 8090
  
spring:
  main: 
    banner-mode: "off"
  cloud:
    gcp:
      project-id: ${PROJECT_ID}
      credentials:
        encoded-key: "${GCP_KEY_FILE_BASE64}"
  
logging:
  level:
    org.springframework: ${LOGGING_LEVEL:INFO} 
    com.sg.pubsub.subscribers.consumer: ${LOGGING_LEVEL_SUBSCRIBER:INFO}
    com.sg.pubsub.controller: ${LOGGING_LEVEL_CONTROLLER:OFF}
    com.sg.pubsub.publisher: ${LOGGING_LEVEL_PUBLISHER:OFF}
    