server:
  servlet:
    context-path: "/tspn/servicedb/v1"
  port: 8089

spring:
  main: 
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/taspen_opty?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    driver: com.mysql.cj.jdbc.Driver
    username: admin
    password: passwd

    hikari:
      maximum-pool-size: 20
      connection-timeout: 60000 ## in milisec
  redis:
    # redis database index (default 0), we use a database with index 3 to avoid conflicts with other databases
    database: 3
    # redis server address (localhost by default)
    host: ${REDIS_HOST}
    # redis port (default 6379)
    port: 6379
    # redis access password (default is empty)
    password:  ${REDIS_PASSWORD}
    # redis connection timeout time (in milliseconds)
    timeout: 0
    # redis connection pool configuration
    pool:
      # Maximum number of connections available (default is 8, negative number means infinite)
      max-active: 8
      # Maximum number of free connections (default is 8, negative number means infinite)
      max-idle: 8
      # Minimum number of idle connections (default is 0, which only works if it is positive)
      min-idle: 0
      # Get the maximum connection waiting time from the connection pool (default is - 1, in milliseconds, and the negative number is infinite)
      max-wait: -1    

thread-pool: 10 ## just random property - no actual meaning

logging:
  level:
    org.springframework: ${LOGGING_LEVEL:INFO}
    org.mybatis: ${LOGGING_LEVEL:INFO}
    org.ehcache: ${LOGGING_LEVEL:INFO}
    com.sg: ${LOGGING_LEVEL:INFO}